apiVersion: apps/v1
kind: Deployment
metadata:
  name: parse-service
  labels:
    app: parse-service
spec:
  replicas: 5
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: parse-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: parse-service
        tier: service
    spec:
      containers:
        - name: parse-service
          image: "misis/parse-service:1.1"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: PORT
              value: "8090"
---
apiVersion: v1
kind: Service
metadata:
  name: parse-service
  labels:
    app: parse-service
    tier: service
spec:
  type: NodePort
  ports:
    - port: 8090
  selector:
    app: parse-service